appli/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.index, name='empty'),
    path('catalogue', views.catalogue, name='catalogue'),
    #to be used for creating pre-filtered links for the catalogue
    path('catalogue/<str:gender>/', views.catalogue, name='pre_filtered_catalogue'),
    path('index', views.index, name= "index"),
    path('filter-data', views.filter_data, name='filter_data'),
    #necessary additional url for the filter to work correctly if you access the catalogue via prefiltered url links
    path('catalogue/<str:gender>/filter-data', views.filter_data, name='filter_data_from_prefiltered'),
    path('product/<int:product_id>/edit_promotion/', views.edit_promotion, name='edit_promotion')
   

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mercadona/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('studiadmin/', admin.site.urls),
    path('appli/', include('appli.urls')),
]

#if settings.DEBUG:  
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appli/models.py
from django.db import models
from django.utils.html import mark_safe
from datetime import date
from decimal import Decimal
from django.conf import settings
from cloudinary.models import CloudinaryField

class Category(models.Model):
    title = models.CharField(max_length=100)
    class Meta:
        verbose_name_plural='Categories'

    def __str__(self):
        return self.title
    
class SizeStandard(models.Model):
    title = models.CharField(max_length=50)
    display_order = models.SmallIntegerField()
    
    def __str__(self):
        return self.title

class SizeShoe(models.Model):
    title = models.CharField(max_length=50)
   
    
    def __str__(self):
        return self.title

class SizePant(models.Model):
    title = models.CharField(max_length=50)


    def __str__(self):
        return self.title

class Gender(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title

#main model for products    
class Product(models.Model):
    product_name =models.CharField(max_length=70)
    product_price = models.DecimalField(max_digits=10, decimal_places=2)
    product_category = models.ForeignKey(Category, on_delete=models.CASCADE)
    product_gender = models.ForeignKey(Gender, on_delete=models.CASCADE, default='')
    product_size_standard = models.ManyToManyField(SizeStandard, blank=True)
    product_size_pants = models.ManyToManyField(SizePant, blank=True)
    product_size_shoes = models.ManyToManyField(SizeShoe, blank=True)
    product_description = models.TextField(blank=True)
    product_promotion_percentage=models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    product_promotion_start_date=models.DateField(blank=True,null=True)
    product_promotion_end_date=models.DateField(blank=True,null=True)
    product_promotion_price=models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    #to upload pictures in dev mode
    if settings.DEBUG == True:
        product_picture=models.ImageField(upload_to='images/')

    #to upload pictures in production mode
    elif settings.DEBUG == False:
        product_picture=CloudinaryField('image')
    
    def __str__(self):
        return self.product_name

    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50"/>'%(self.product_picture.url))
    
    
    def is_discount(self):
        "returns if the item is on promotion and the promotion price"
        today = date.today()
        if self.product_promotion_start_date < today and self.product_promotion_end_date > today:
            return True
        else:
            return False
    
    

 

appli/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.template import loader
from .models import *
from django.template.loader import render_to_string
from django.db.models import Max, Min
from django.shortcuts import render, redirect


def index(request):
    template = loader.get_template('appli/index.html')
    context = {}
    return HttpResponse(template.render(context,request))

#main catalogue view. Can be used a gender value to create links to prefiltered catalogue
def catalogue(request, gender=''):
    
    if gender == '':
        data = Product.objects.all().order_by('product_name')
    #logic to create pre-filtered catalogues pages    
    elif gender =="homme":
        data = Product.objects.all().order_by('product_name')
        data = data.filter(product_gender__title = 'homme') 
    elif gender =="femme":
        data = Product.objects.all().order_by('product_name')
        data = data.filter(product_gender__title = 'femme') 
    elif gender =="enfant":
        data = Product.objects.all().order_by('product_name')
        data = data.filter(product_gender__title = 'enfant')

    size_standard = SizeStandard.objects.all().order_by('display_order')
    size_pants = SizePant.objects.all().order_by('title')
    size_shoes = SizeShoe.objects.all().order_by('title')
    gender_list = Gender.objects.all().order_by('title')
    categorie_list = Category.objects.all().order_by('title')
    minMaxPrice = data.aggregate(Min('product_price'),Max('product_price'))

    template = loader.get_template('appli/catalogue.html')
    context = {"data": data, "size_standard": size_standard, "size_pants": size_pants, "size_shoes" : size_shoes,
    "gender_list":gender_list, 'categorie_list':categorie_list, "minMaxPrice":minMaxPrice}

    return HttpResponse(template.render(context,request))

#view handling filtered products
def filter_data(request, gender =''):
    #if filter is called from basic catalogue page, then no gender variable is given in the url, else there is one and we use it to define gender_list
    if gender == '':
        gender_list=request.GET.getlist('gender_list[]')   
    else:
        gender_list=[gender]     
    size_standard=request.GET.getlist('size_standard[]')
    size_pants=request.GET.getlist('size_pants[]')
    size_shoes=request.GET.getlist('size_shoes[]')
    categorie_list=request.GET.getlist('categorie_list[]')
    

    maxPrice=request.GET.get('maxPrice', '0.00')
   
    allProducts=Product.objects.all().order_by('-id').distinct()
    #filters logic
    allProducts=allProducts.filter(product_price__lte=maxPrice)
    if len(size_standard)>0 or len(size_pants)>0 or len(size_shoes)>0:
       allProducts=allProducts.filter(product_size_standard__title__in = size_standard).distinct() | allProducts.filter(product_size_pants__title__in = size_pants).distinct() | allProducts.filter(product_size_shoes__title__in = size_shoes).distinct()
    if len(categorie_list)>0:
        allProducts = allProducts.filter(product_category__title__in = categorie_list).distinct()
    if len(gender_list)>0:
        allProducts=allProducts.filter(product_gender__title__in = gender_list).distinct()
                    
    
    context ={'data':allProducts}        
    t=render_to_string('appli/ajax-product-list.html', context)
    return JsonResponse({'data': t})


def edit_promotion(request, product_id):
    # Retrieve the product object based on the product_id
    product = Product.objects.get(id=product_id)

    if request.method == 'POST':
        # Update the promotion attributes based on the form data
        product.product_promotion_percentage = request.POST['product_promotion_percentage']
        product.product_promotion_start_date = request.POST['product_promotion_start_date']
        product.product_promotion_end_date = request.POST['product_promotion_end_date']
        product.product_promotion_price= product.product_price - product.product_price* (Decimal(str(product.product_promotion_percentage))/100)
        product.save()

        # Redirect back to the product change page in the admin site
        return redirect('admin:appli_product_changelist')

    # Render the custom admin view for editing promotion attributes
    context = {
        'product': product,
    }
    return render(request, 'edit_promotion.html', context)

appli/templates/appli/ajax-product-list.html
{% if data %} {% for product in data %} 
{% if product.product_promotion_start_date and product.product_promotion_end_date and product.is_discount %}
<div class="col-lg-4 col-md-6">
  <div class="product__item">
    <div class="product__item__pic set-bg">
      <div class="label promo">Promo</div>
      <img src="{{ product.product_picture.url }}" class="product_item_img" />

      <ul class="product__hover">
        <li>
          <a href="{{ product.product_picture.url }}" class="image-popup"
            ><span class="arrow_expand"></span
          ></a>
        </li>
        <li>
          <a href="#"><span class="icon_heart_alt"></span></a>
        </li>
        <li>
          <a href="#"><span class="icon_bag_alt"></span></a>
        </li>
      </ul>
    </div>
    <div class="product__item__text">
      <h6><a href="#">{{product.product_name}}</a></h6>
      <div class="rating">
        <i class="fa fa-star"></i>
        <i class="fa fa-star"></i>
        <i class="fa fa-star"></i>
        <i class="fa fa-star"></i>
        <i class="fa fa-star"></i>
      </div>
      <div class="product__price_discounted">
        {{product.product_promotion_price|floatformat:2}} €
      </div>
    </div>
  </div>
</div>

{% else %}
<div class="col-lg-4 col-md-6">
  <div class="product__item">
    <div class="product__item__pic set-bg">
      <img src="{{ product.product_picture.url }}" class="product_item_img" />

      <ul class="product__hover">
        <li>
          <a href="{{ product.product_picture.url }}" class="image-popup"
            ><span class="arrow_expand"></span
          ></a>
        </li>
        <li>
          <a href="#"><span class="icon_heart_alt"></span></a>
        </li>
        <li>
          <a href="#"><span class="icon_bag_alt"></span></a>
        </li>
      </ul>
    </div>
    <div class="product__item__text">
      <h6><a href="#">{{product.product_name}}</a></h6>
      <div class="rating">
        <i class="fa fa-star"></i>
        <i class="fa fa-star"></i>
        <i class="fa fa-star"></i>
        <i class="fa fa-star"></i>
        <i class="fa fa-star"></i>
      </div>
      <div class="product__price">{{product.product_price}} €</div>
    </div>
  </div>
</div>
{% endif %} {% endfor %} {% endif %}

appli/templates/edit_promotion.html
{% extends 'admin/base.html' %}

{% block content %}
<h1>Edit promotion values for {{ product.product_name }}</h1>
<form method="post">
  {% csrf_token %}
  <label for="id_product_promotion_percentage">Promotion Percentage:</label>
  <input type="number" name="product_promotion_percentage" id="id_product_promotion_percentage" step="0.01" value="{{ product.product_promotion_percentage }}" required>
  <br>
  <label for="id_product_promotion_start_date">Promotion Start Date:</label>
  <input type="date" name="product_promotion_start_date" id="id_product_promotion_start_date" value="{{ product.product_promotion_start_date|date:'Y-m-d' }}" required>
  <br>
  <label for="id_product_promotion_end_date">Promotion End Date:</label>
  <input type="date" name="product_promotion_end_date" id="id_product_promotion_end_date" value="{{ product.product_promotion_end_date|date:'Y-m-d' }}" required>
  <br>
  <input type="submit" value="Save">
</form>
{% endblock %}